// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aatteeoqwkukncqnihbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdHRlZW9xd2t1a25jcW5paGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDk4MzEsImV4cCI6MjA2NjYyNTgzMX0.mHCBj5ZJk8JJ5IUlFS31DJVmw615QyHDC611SdJCypY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);